### ISSUE TITLE
components not working

### ISSUE THREAD

**Issue by mredux** [Sopur/Discord-user-bots#11]
Hi 
I am trying to send components  but idk they are not working as excepted.
![This is an image](https://image.prntscr.com/image/zMA7AXdPQ9mfgHMHxx9LMQ.png)
![This is an image](https://image.prntscr.com/image/aaK0zaHbT3qB_tF9KmbUkA.png)
![This is an image](https://image.prntscr.com/image/N_eqTxenTdGCyGObm6BgVQ.png)
thanks

**Comment by Sopur** [comment]
To my knowledge, the components object is not available for normal users. Hints why it's simply a property and nothing more in the documentation.
