### ISSUE TITLE
Is there any event listener to know new member join the server?

### ISSUE THREAD

**Issue by harrykc** [Sopur/Discord-user-bots#12]
The server do not have welcome channel, so is there any event listener to know new member join the server(not server owner, just one of the member on that server)?

**Comment by mredux** [comment]
use this ? 
`guild_member_add: function (message) {},`

**Comment by harrykc** [comment]
cant, I am the normal member on that server

**Comment by Sopur** [comment]
Do you mean when you join a server or when a member does?

**Comment by harrykc** [comment]
When a member join the server.

**Comment by Sopur** [comment]
The `guild_member_add` function should be triggered when a member joins.
```
const Discord = require("discord-user-bots");
const client = new Discord.Client("Token goes here.");

client.on.ready = function () {
    console.log("Client online!");
};

client.on.guild_member_add =  function (user) {
  console.log("User joined/got added!", user);
}
```
