### ISSUE TITLE
captcha error in joining guilds

### ISSUE THREAD

**Issue by gurumnyang** [Sopur/Discord-user-bots#16]
`client.join_guild(
            String(link) // The Discord invite
        ).then(e => console.log(e));`

error is
`{
  captcha_key: [ 'You need to update your app to join this server.' ],
  captcha_sitekey: '4c672d35-0701-42b2-88c3-78380b0db560',
  captcha_service: 'hcaptcha'
}
`

**Comment by Sopur** [comment]
Joining guilds through Discord User Bots is deprecated and not currently supported. However, I am planning a release with this feature enabled when Node 18.0 releases.
