### ISSUE TITLE
Examples on how to add a bot to a testing server, and how to join a server with this pkg?

### ISSUE THREAD

**Issue by ghost** [Sopur/Discord-user-bots#3]
The title says it all, btw I can help you with this if you want @Sopur 😄 
I work on a discord list, and for automating joining server or testing bot, I really need this package :)

**Comment by Sopur** [comment]
To answer your first question, the join_guild function is the 3rd function documented in the README.md file. Here is what it looks like:
```
//               The server invite
//                      v
client.join_guild("invite-code", false);
//                                 ^
// Make this second parameter true if you want to use a http link, it's false by defualt
```
Full example:
```
const Discord = require("discord-user-bots");
const client = new Discord.Client("Token goes here.");

client.on.ready = function () {
    console.log("Client online! Joining...");
    client.join_guild("invite-code", false); // False neaning it's a raw invite code and not a link
};
```
Be careful however,this function is a little dated and joining with this may lead to an account disable (I suggest never using this on your main until I fix it).

To answer your second question, I would be delighted if you were to help me with this package. As long as you have a basic understanding of the Discord API (And copying fetch requests from real clients) you can do whatever you like. If you want, I can add you to this project directly.

**Comment by ghost** [comment]
oh nice, and thanks for the quick reply!
btw if you want i can make this npm package more popular than djs within a day if you want to ;)

**Comment by Sopur** [comment]
I am flattered. If you want to get in contact with me you can on Discord at Sopur#3550. Cheers!
