### ISSUE TITLE
Get channel id of someone by his id

### ISSUE THREAD

**Issue by JgBr123** [Sopur/Discord-user-bots#31]

**Comment by lf94** [comment]
Do you mean get multiple channel ids? I don't think this is possible even in the official client.

**Comment by Sopur** [comment]
Can you specify further what you're trying to do? Are you trying to copy the channel ID of the DM from the official client? Or from code?

**Comment by JgBr123** [comment]
closing the issue because it was 2 years ago, and i dont even remember what was the problem, lol
