### ISSUE TITLE
How to sed direct messege to another user?

### ISSUE THREAD

**Issue by Frenzied-Dog** [Sopur/Discord-user-bots#32]
It seems that client.send can only sed message to a channel.

**Comment by Pig0Brine** [comment]
Dms still take place in channels

**Comment by Sopur** [comment]
I'm guessing your confusion is coming from the fact that right clicking "copy id" on a DM does not give a channel ID user accounts can use. If you want to get the ID of specific DMs, open up inspect element, go to the network tab, and start typing in the DM you want to copy. You should see that the discord client sent a typing event which contains the correct ID of the DM in the URL. If you're using the web version of Discord, click on the DM of your choice and copy the DM ID located in the URL of the page.
