### ISSUE TITLE
Bot can't see messages that are marked as replies

### ISSUE THREAD

**Issue by Ambassador4ik** [Sopur/Discord-user-bots#34]
I have tried the bot on multiple servers, It neves sees messages that are replies, whether it is a reply to bot's message or not. 
I also mentioned that on some servers it cannot see any messages at all, mostly on big ones such as Homework Help

**Comment by Sopur** [comment]
To receive events that are message replies you have to use the `client.on.reply` event listener. All event listeners are documented in the README.
