### ISSUE TITLE
Possible red flag.

### ISSUE THREAD

**Issue by ItsCEED** [Sopur/Discord-user-bots#4]
wss://gateway.discord.gg/?encoding=json&v=9

Using the socket without ERLPACK, will probably flag and terminate the account at some instances, discord is checking everything when they are in full ban mode and also along the weekends.

**Comment by Sopur** [comment]
Honestly I couldn't even install Discord's ERLPACK without erroring, and I'm afraid that might make my package harder to use. I have never seen any account disable because of this, but it could happen in the future. Thanks for letting me know! I'll look into this if it becomes a bigger problem.
