### ISSUE TITLE
{ message: 'Unknown Channel', code: 10003 }

### ISSUE THREAD

**Issue by ghost** [Sopur/Discord-user-bots#48]
client.on.ready = async function() {
    msg = await client.fetch_messages(1, "970308424422293504");
    console.log(msg);
};

>>> { message: 'Unknown Channel', code: 10003 }

but id is correct

**Comment by Sopur** [comment]
Can you please give more information? Is this a DM? Using "Copy ID" on a DM doesn't return the channel ID of the DM. Also, Discord will generally return a bad response when requesting to fetching one message. Try fetching 50 or 100.

**Comment by ghost** [comment]
oh, sorry, I copied the id of the server and not the channel
