### ISSUE TITLE
Error When User Invalid Token

### ISSUE THREAD

**Issue by iamvinthanks** [Sopur/Discord-user-bots#57]
When I use 
`client = new Discord.Client(token);`

and when token is invalid got message

```
discord-user-bots\src\client\client.js:58 } else throw new DiscordAPIError(`Discord rejected token "${token}" (Not valid)`);
DiscordAPIError: Discord API Error: Discord rejected token "XXXXxxxxx" (Not valid)

```
How to handle this error?

**Comment by Sopur** [comment]
Just added this feature in the 2.0.0 update. DUB now works just like Discord.js, with a ".login" method.
